name: Build and deploy to GitHub Pages

on:
  push:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2.3.1

      - name: Install, lint, build 🔧
        env:
          API_KEY: ${{secrets.REACT_APP_MOCKAPI_API_SECRET}}
        run: |
          echo "==="
          echo "Creating .env file with API key secret:"
          echo "REACT_APP_MOCKAPI_API_SECRET=${API_KEY}" > .env
          echo "==="
          npm install
          npm run lint:js
          npm run build

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@4.1.0
        with:
          branch: gh-pages
          folder: build
